
configfile: "config.yml"


rule all:
    input:
        coords=expand(
            "tpl-{template}_dir-{dir}_hemi-{hemi}_space-corobl_label-{label}_desc-laplace_coords.nii.gz",
            template=config["template"],
            dir=["AP", "PD", "IO"],
            hemi="R",
            label=["hipp", "dentate"],
        ),


ruleorder: laplace_dentate_AP > laplace_coords


rule laplace_coords:
    input:
        lbl=lambda wildcards: config["laplace_labels"][wildcards.label][wildcards.dir][
            "img"
        ].format(**wildcards),
    params:
        gm_labels=lambda wildcards: config["laplace_labels"][wildcards.label][
            wildcards.dir
        ]["gm"],
        src_labels=lambda wildcards: config["laplace_labels"][wildcards.label][
            wildcards.dir
        ]["src"],
        sink_labels=lambda wildcards: config["laplace_labels"][wildcards.label][
            wildcards.dir
        ]["sink"],
        convergence_threshold=1e-5,
        max_iters=10000,
    output:
        coords="tpl-{template}_dir-{dir}_hemi-{hemi}_space-corobl_label-{label}_desc-laplace_coords.nii.gz",
    log:
        "logs/tpl-{template}_dir-{dir}_hemi-{hemi}_space-corobl_label-{label}_desc-laplace_coords.txt",
    script:
        "../../workflow/scripts/laplace_coords.py"


rule laplace_dentate_AP:
    """ we just mask this from the hipp label"""
    input:
        lbl=lambda wildcards: config["laplace_labels"][wildcards.label][wildcards.dir][
            "img"
        ].format(**wildcards),
        coords="tpl-{template}_dir-AP_hemi-{hemi}_space-corobl_label-hipp_desc-laplace_coords.nii.gz",
    params:
        gm_labels=lambda wildcards: config["laplace_labels"][wildcards.label][
            wildcards.dir
        ]["gm"],
    output:
        coords="tpl-{template}_dir-{dir,AP}_hemi-{hemi}_space-corobl_label-{label,dentate}_desc-laplace_coords.nii.gz",
    shell:
        "c3d {input.lbl} -retain-labels {params.gm_labels} -binarize {input.coords} -multiply -o {output.coords}"
