blank_issues_enabled: false
contact_links:
  - name: Hippunfold Issues
    url: https://github.com/khanlab/hippunfold
    about: For issues, feature requests, or questions specifically about hippunfold, please open an issue here.