#list of analysis levels in the bids app 
analysis_levels: 
 - participant
 - group_create_atlas
 - group
  

#mapping from analysis_level to set of target rules or files
targets_by_analysis_level:
  participant:
    - 'all'  # if '', then the first rule is run
  group_create_atlas:
    - 'all_create_atlas'
  group:
    - 'all_group_tsv'

#this configures the pybids grabber - create an entry for each type of input you want to grab
# indexed by name of input
#   dictionary for each input is passed directly to pybids get()
#    https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html#bids.layout.BIDSLayout.get


pybids_inputs:
  T1w:
    filters:
      suffix: 'T1w'
      extension: '.nii.gz'
      datatype: 'anat'
    wildcards:
      - subject
      - session
      - acquisition
      - run
  T2w:
    filters:
      suffix: 'T2w'
      extension: '.nii.gz'
      datatype: 'anat'
    wildcards:
      - subject
      - session
      - acquisition
      - run
  flair:
    filters:
      suffix: 'FLAIR'
      extension: '.nii.gz'
      datatype: 'anat'
    wildcards:
      - subject
      - session
      - acquisition
      - run
  dsegtissue:
    filters:
      suffix: 'dseg'
      extension: '.nii.gz'
      datatype: 'anat'
      desc: 'tissue'
    wildcards:
      - subject
      - session
      - hemi
      - acquisition
      - run


  dsegsubfields:
    filters:
      suffix: 'dseg'
      extension: '.nii.gz'
      datatype: 'anat'
      desc: 'subfields'
    wildcards:
      - subject
      - session
      - hemi
      - acquisition
      - run


#configuration for the command-line parameters to make available
# passed on the argparse add_argument()
parse_args:

  --modality:
    help: 'Type of image to run hippunfold on. superres will attempt super-resolution sampling as T1w + 1/T2w + 1/flair. For dsegtissue and be sure to match the label scheme applied in the look up table (lut) online. For best performance, please also make sure the input is approximately aligned to the template space, with separate hemi-L|R in the name(s). (default: %(default)s)'
    required: False
    choices:
      - T1w
      - T2w
      - flair
      - superres
      - dsegtissue
    default: 'T1w'

  --nnunet_model:
    help: 'Set the nnU-net model to use for segmentation. (default: %(default)s)'
    required: False
    choices:
      - synthlayer
    default: 'synthlayer'

  --skip_inject_template_labels:
    help: 'Set this flag to skip post-processing template injection into CNN segmentation. Note this will disable generation of DG surfaces. (default: %(default)s)'
    default: False
    action: 'store_true'

  --inject_template:
    choices:
      - 'upenn'
    default: 'upenn'
    help: 'Set the template to use for shape injection. (default: %(default)s)'

  --inject_template_smoothing_factor: 
    help: 'Scales the default smoothing sigma for gradient and warp in template shape injection. Using a value higher than 1 will use result in a smoother warp, and greater capacity to patch larger holes in segmentations. Try setting to 2 if nnunet segmentations have large holes. Note: the better solution is to re-train network on the data you are using (default: %(default)s)'
    default: 1.0

  --crop_res:
    help: 'Sets the bounding box resolution for the crop original modality (e.g. cropT1w space). Under the hood, hippUnfold operates at higher resolution than the original image, so this tries to preserve some of that detail. (default: %(default)s)'
    default: '0.2x0.2x0.2mm'

  --crop_box:
    help: 'Sets the bounding box size for the crop original modality (e.g. cropT1w space). Make this larger if your hippocampi in crop{T1w,T2w} space are getting cut-off. This must be in voxels (vox) not millimeters (mm). (default: %(default)s)'
    default: '256x256x256vox'

  --use_gpu:
    help: 'Enable gpu for inference by setting resource gpus=1 in run_inference rule (default: %(default)s)'
    default: False
    action: 'store_true'

  --nnunet_enable_tta:
    help: 'Enable test-time augmentation for nnU-net inference, slows down inference by 8x, but potentially increases accuracy (default: %(default)s)'
    default: False
    action: 'store_true'

  --output_spaces:
    choices: 
      - 'T1w'
      - 'corobl'
    nargs: '+'
    default: []
    help: 'Sets output spaces for results (default: %(default)s)'

  --hemi:
    choices:
      - 'L'
      - 'R'
    default:
      - 'L'
      - 'R'
    nargs: '+'
    help: 'Hemisphere(s) to process (default: %(default)s)'

  --laminar_coords_method:
    choices:
      - 'laplace'
      - 'equivol'
      - 'equidist'
    default: 'equidist'
    help: 'Method to use for laminar coordinates. Equivol and equidist are from the laynii LN2_LAYERS tool.  (default: %(default)s)' 

  --autotop_labels:
    choices:
      - 'hipp'
      - 'dentate'
    default:
      - 'hipp'
      - 'dentate'
    nargs: '+'
    help: 'Run hipp (CA + subiculum) alone or include dentate (default: %(default)s)'

  --enable-bids-validation:
    help: |
      Enable validation of BIDS dataset. BIDS validation would be performed
      using the bids-validator plugin (if installed/enabled) or with the pybids
      validator implementation (if bids-validator is not installed/enabled).
    dest: "plugins.validator.skip"
    action: "store_false"
    default: True

  --version:
    help: 'Print the version of HippUnfold'
    action: version
    version: "1.5.2-pre.2"


# --- surface specific configuration -- 

autotop_labels:
  - 'hipp'
  - 'dentate'

surf_types:
  hipp:
    - midthickness
    - inner
    - outer
  dentate:
    - midthickness
    - inner
    - outer

gifti_metric_types:
  hipp:
    - gyrification.shape 
    - curvature.shape
    - thickness.shape
  dentate:
    - gyrification.shape 
    - curvature.shape
    - thickness.shape
  
cifti_metric_types: 
  hipp:
    - gyrification.dscalar
    - curvature.dscalar
    - thickness.dscalar
  dentate:
    - gyrification.dscalar
    - curvature.dscalar
    - thickness.dscalar

#--- workflow specific configuration -- 


xfm_identity: resources/etc/identity_xfm.txt
xfm_identity_itk: resources/etc/identity_xfm_itk.txt

template: 'CITI168'

template_files:
  CITI168:
    T1w: T1w_space-corobl.nii.gz
    xfm_corobl: CoronalOblique_rigid.txt
    Mask_crop: Mask_200umCoronalOblique_hemi-{hemi}.nii.gz
  upenn:
      T1w: tpl-upenn_desc-hipptissue_dseg.nii.gz
      dseg: tpl-upenn_desc-hipptissue_dseg.nii.gz
      layers: tpl-upenn_desc-layers_dseg.nii.gz
      dseg_dentate: tpl-upenn_desc-hippdentate_dseg.nii.gz # hack: separate files for DG
      coords: tpl-upenn_dir-{dir}_label-{label}_coords.nii.gz
      hemi_wildcards:
        - R
   

tissue_atlas_mapping:
  tissue:
    dg: 5,6
    srlm: 7
    cyst: 8
  default: 
    dg: 6
    srlm: 7
    cyst: 8

#these will be downloaded to ~/.cache/hippunfold
resource_urls:
  nnunet_model:
    synthlayer: 'zenodo.org/record/8184230/files/trained_model.3d_fullres.Task100_synthlayer.nnUNetTrainerV2.model_best.tar'
  atlas:
    multihist7: 'www.dropbox.com/scl/fi/g07u7la7v1kwfgsty6ujc/atlas-multihist7_20250108.zip?rlkey=bi7wbdsm93upgnn3bmlv4f1hx&st=5iv33isc&dl=0'
  template:
    CITI168: 'files.ca-1.osf.io/v1/resources/v8acf/providers/osfstorage/65395bf0282745121fb86a93/?zip='
    upenn: 'files.ca-1.osf.io/v1/resources/v8acf/providers/osfstorage/65395c1613d27b122a94ca09/?zip='


unfold_vol_ref:
  hipp:
    dims:
      - '256'
      - '128' 
      - '16'
    voxdims:
      - '0.15625'
      - '0.15625'
      - '0.15625'
    origin:
      - '0'
      - '200'
      - '0'
    extent:
      - '40'
      - '20'
      - '2.5'
    orient: RPI

  dentate:
    dims:
      - '256'
      - '32'
      - '16'
    voxdims:
      - '0.15625'
      - '0.15625'
      - '0.15625'
    origin:
      - '0'
      - '200'
      - '0'
    extent:
      - '40'
      - '5'
      - '2.5'
    orient: RPI


# space for uniform unfolded grid:
#  currently only used for interpolating hipp subfields on surface
unfold_mesh_ref:
  dims:
   - 254
   - 126
  start:
   - 0.234375
   - 0.234375
  end:
   - 39.765625
   - 19.765625

shape_inject:
  labels_reg: 
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  labels_reinsert:
    - 8
  label_smoothing_stdev: '0.5x0.5x0.5mm'



laplace_labels:
  hipp:
    AP: 
      gm:
        - 1
        - 8
      src:
        - 5
      sink:
        - 6
    PD:
      gm:
        - 1
        - 8
      src:
        - 3
      sink:
        - 8   
    IO:
      gm:
        - 1
      src:
        - 2
        - 4
        - 7
        - 9
      sink:
        - 0 
        - 10
  dentate:
    AP:
      gm:
        - 8
      src:
        - 5
      sink:
        - 6
    PD:
      gm:
        - 8
      src:
        - 9
      sink:
        - 10
    IO:
      gm:
        - 8
      src:
        - 1
        - 3
      sink:
        - 2
        - 4
        - 7
        - 9
        - 10
        - 0

      
tight_crop_labels: #defines what labels to use for tight cropping (for upsampled ref)
  hipp:
    - 1
  dentate:
    - 8

laminar_coords_res:
  hipp: 0.3x0.3x0.3mm
  dentate: 0.1x0.1x0.1mm

resample_dseg_for_templatereg: 0.3x0.3x0.3mm
unfoldreg_padding: 0x0x0vox

surf_thresholds:
  inner: 0
  outer: 1
  midthickness: 0.5
