name: Publish Conda package

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to simulate, e.g. v2.1.0a0"
        required: true
        type: string

      upload:
        description: "Actually upload package"
        required: true
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: >-
            ${{ github.event_name == 'release'
                && github.event.release.tag_name
                || github.ref }}
          fetch-depth: 0

      - name: Build and publish
        uses: khanlab/actions/.github/actions/action-pixi_task-publish@df4211abe672b61c81f4177eef5b9516edf2944e
        with:
          release-tag: >-
            ${{ github.event_name == 'release'
                && github.event.release.tag_name
                || inputs.release_tag }}
          channel: akhanf/khanlab
          api-key: ${{ secrets.PREFIX_API_KEY }}
          upload: >-
            ${{ github.event_name == 'release'
                || inputs.upload }}


