name: Hippunfold PR Wet-Run (Ephemeral Runner)

on:
  workflow_dispatch:
  pull_request:
    # types: [labeled]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  actions: write

env:
  OS_AUTH_TYPE:                      "v3applicationcredential"
  OS_AUTH_URL:                       "https://arbutus.cloud.computecanada.ca:5000/v3"
  OS_USERNAME:                       "djay"
  OS_USER_DOMAIN_NAME:               "CCDB"
  OS_APPLICATION_CREDENTIAL_ID:      ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: "${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}"
  RUNNER_PAT: ${{ secrets.RUNNER_PAT }}


jobs:
  launch-runner:
    # if: >
    #   (github.event_name == 'pull_request' &&
    #      github.event.action == 'labeled' &&
    #      github.event.label.name == 'ready-for-wet-run')
    #   ||
    #   (github.event_name == 'workflow_dispatch')
    uses: khanlab/actions/.github/workflows/workflow-pr_task-launchRunner.yml@djay/add-wetRunTestLogic
    with:
      pr_number: ${{ github.event.pull_request.number }}
      repository: ${{ github.repository }}
      repository_name: ${{ github.event.repository.name }}
      repository_owner: ${{ github.repository_owner }}

  run-wet-run:
    needs: launch-runner
    runs-on: [self-hosted, ephemeral, wet-run]
    defaults:
      run:
        shell: bash -l {0}
    timeout-minutes: 60  # max 1 hour

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Miniforge and mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        mamba-version: "*"
        use-mamba: true
        conda-solver: libmamba
        auto-activate-base: true

    - name: Install snakebids
      run: |
        mamba install snakebids -c bioconda -c conda-forge -y

    - name: Download lowresMRI dataset
      run: |
        mkdir -p /mnt/data
        cd /mnt/data
        wget -q -O lowresMRI.zip "https://files.ca-1.osf.io/v1/resources/k2nme/providers/osfstorage/66759a948dfe890189cb7178/?zip="
        unzip -q lowresMRI.zip -d lowresMRI

    - name: Setup env for hippunfold
      run: |
        echo "HIPPUNFOLD_CACHE_DIR=/mnt/test_data/hippunfold_cache_dir" >> $GITHUB_ENV

    - name: activate snakebids-env and run wet run
      run: |
        PR=${{ github.event.pull_request.number }}
        git fetch origin pull/${PR}/head:pr-${PR}
        git checkout pr-${PR}
        ./hippunfold/run.py /mnt/data/lowresMRI /mnt/test_out participant --participant-label 01 --modality T1w --cores all --conda-prefix /mnt/conda-envs

  cleanup:
    needs: [launch-runner, run-wet-run]
    if: always()
    uses: khanlab/actions/.github/workflows/workflow-pr_task-removeRunner.yml@djay/add-wetRunTestLogic
    with:
      pr_number: ${{ github.event.pull_request.number }}
      repository: ${{ github.repository }}
      repository_name: ${{ github.event.repository.name }}
      vm_id: ${{ needs.launch-runner.outputs.vm_id }}