
hippunfold_dir: '/scratch/akhanf/1_dev/hippunfold_isovol/test_hcp/output_hcpUR100'

num_bins: '100'

autotop_labels:
  - autotopDG
#  - autotopHipp

test_subjects:
  - '100307' 

in_surfarea:
  dims:
   - 254
   - 126
  start:
   - 0.234375
   - 0.234375
  end:
   - 39.765625
   - 19.765625

surf_to_io:
  midthickness: 1.171875
  inner: 0.078125
  outer: 2.265625

targetareas:
 - '1.6'
 - '1.4'
 - '1.2'
 - '1.0'
 - '0.9'
 - '0.8'
 - '0.7'
 - '0.6'
 - '0.5'
 - '0.4'
 - '0.3'
 - '0.2'
 - '0.15'
 - '0.12'
 - '0.1'
 - '0.08'
 - '0.06'
 - '0.04'
 - '0.02'

#this is filled in by hand (since they are approximate)
#density_to_area: #this was for Hipp
#  '400': '2.3'
#  '2k': '0.53'
#  '7k': '0.15'

density_to_area: #this is for DG
  '400': '1.0'
  '2k': '0.2' 
  '7k': '0.06' #DG is actually 3k with ~0.5mm spacing



